### ISSUE TITLE
matplotlib 한글 출력시 깨짐 문제

### ISSUE THREAD

**Issue by waverDeep** [waverDeep/FinDataAnalysis#2]
한글 출력시 깨짐 문제는 어떻게 해결하나요?
@mainarchive 
@Happy0Hyun

**Comment by mainarchive** [comment]
### ✔️ 한글 폰트 사용 해결 : font_path 에 사용하고자 하는 한글 폰트의 경로를 작성
from matplotlib import font_manager, rc
font_path = "C:/Windows/Fonts/NanumBarunpenR.ttf"
font = font_manager.FontProperties(fname=font_path).get_name()
rc('font', family=font)

**Comment by mainarchive** [comment]
이거 아닌가
알고 있지 않냐요

**Comment by waverDeep** [comment]
저는 이러한 오류가 뜨더라구요.. ㅋㅋ
`findfont: Font family ['NanumSquareRound'] not found. Falling back to DejaVu Sans.
/usr/local/lib/python3.6/dist-packages/matplotlib/backends/backend_agg.py:211: RuntimeWarning: Glyph 44396 missing from current font.
  font.set_text(s, 0.0, flags=flags)
/usr/local/lib/python3.6/dist-packages/matplotlib/backends/backend_agg.py:211: RuntimeWarning: Glyph 47196 missing from current font.
  font.set_text(s, 0.0, flags=flags)
findfont: Font family ['NanumSquareRound'] not found. Falling back to DejaVu Sans.
/usr/local/lib/python3.6/dist-packages/matplotlib/backends/backend_agg.py:211: RuntimeWarning: Glyph 49548 missing from current font.
  font.set_text(s, 0.0, flags=flags)`

**Comment by mainarchive** [comment]
'NanumSquareRound'라는 한글 폰트가 노트북에 있는건 맞나여 ?
아니면 다른 폰트로 다시 해보세욤, 저도 어떤 글씨체는 안되더라고요 ,, (머쓲)

**Comment by waverDeep** [comment]
@mainarchive 
제가 docker 기반으로 Jupyter를 열고 있어서 저게 안됬던 거네요 ㅎ
[https://teddylee777.github.io/visualization/matplotlib-ubuntu-%ED%95%9C%EA%B8%80%ED%8F%B0%ED%8A%B8%EC%84%A4%EC%B9%98](도커 환경에서 jupyter notebook 한글 깨짐 해결)
이걸로 해결했습니다 ㅎ

**Comment by mainarchive** [comment]
도커가 뭔지 모르지만 나이스 하네여 ,, 😅

**Comment by waverDeep** [comment]
감사합니다!
